### ISSUE TITLE
Sencha Touch 2 Compatibility

### ISSUE THREAD

**Issue by ianserlin** [elmasse/Ext.ux.Cover#1]
What help do you need to make Cover fully compatible with ST2?

I tried the version from master but the reflections are solid gradients.

I tried the version from the sencha-touch-2 branch but Ext.util.Offset is not available as part of the sdk and no combination of the two (Cover.js, cover.css) seems to work correctly.

This would be a great component to have available.

**Comment by elmasse** [comment]
Hi Ian,

The sencha-touch-2 branch is not updated. It was used for the transition. I should remove it.

I'm using sencha touch 2 ga final version from cachefly

```
 <script type="text/javascript" src="http://extjs.cachefly.net/touch/sencha-touch-2.0.0/sencha-touch-all.js"></script>
```

Coverflow is working 100% in ST2 only for iOS devices right now. Have heard that it worked properly in Playbooks as well. Sadly, no Android browser (not even ICS) support perspective and transform3d properties properly yet. And, regarding the reflections, they are not yet working properly neither in Android devices :( - taking aside what that implies in term of performance -

Let me know
