### ISSUE TITLE
View integration

### ISSUE THREAD

**Issue by Itachi-san** [elmasse/Ext.ux.Cover#2]
First of, I just wanna thank you gor this greate Extension,
I'm new to sencha, and I wanna integrate your extension into a view, I'm using the initialize function but I have a lot errors, that I don't even understant
So could you please give me a code sample showing how to embed your ext into a new view?

Thanks a lot :D

**Comment by elmasse** [comment]
Itachi-san, 

Take a look into the demo, here https://github.com/elmasse/Ext.ux.Cover/blob/master/demo/demo.js#L12-50 you create a cover view instance and here https://github.com/elmasse/Ext.ux.Cover/blob/master/demo/demo.js#L65 we are adding that instance to a view, in this case into a TabPanel.
If that is not what you are looking for let me know a little bit more about what are you trying to do.

Thanks
Max

**Comment by Itachi-san** [comment]
Thanks a lot for answer, it was so helpfull
