### ISSUE TITLE
Scrolling is too fast

### ISSUE THREAD

**Issue by steffenborup** [elmasse/Ext.ux.Cover#3]
Thanks for a great plugin! I am using it together with Sencha Touch 2.2 and everything works perfectly, except that the covers move way too fast when dragging. Any idea on how to resolve this?

**Comment by steffenborup** [comment]
I changed the onDrag function to the following, and now everything runs smoothly:

```
onDrag: function(e){
    var curr = this.getOffset(),
        offset,
        ln = this.getViewItems().length,
        selectedIndex,
        delta = (e.deltaX - e.previousDeltaX);

    //slow down on border conditions
    selectedIndex = this.getSelectedIndex();

    if ((selectedIndex === 0 && e.deltaX > 0) || (selectedIndex === ln - 1 && e.deltaX < 0)) {
        delta *= 0.5;
    }

    offset = curr + delta;

    this.setOffset(offset, true);
},
```

**Comment by elmasse** [comment]
Edited: applied onDrag as stated in previous comment.

Sorry @steffenborup I just see this issue, for some weird reason it didn't go thru my email :(
Anyway, I will mark this as feature request to add frictionFactor property so you can modify the drag velocity without having to override any function.
